'use strict';

var storeHours = ['6am','7am','8am','9am','10am','11am','12pm','1pm','2pm','3pm','4pm','5pm','6pm','7pm'];
var locationHourlySales = [];
var locationData = [
  // city min max avg hourly daily
  ['Seattle', 23, 65, 6.3 , [], 0],
  ['Tokyo', 3, 24, 1.2, [], 0],
  ['Dubai', 11, 38, 3.7, [], 0],
  ['Paris', 20, 38, 2.3, [], 0],
  ['Lima', 2, 16, 4.6, [], 0]
];
// Defining the object constructor (nothing is executing, it's just defining it)
var Store = function(city, minHourlyCustomers, maxHourlyCustomers, avgCookiesPerCust, hourlySales, dailySales){
  // this.city is a variable that will be assigned the value of whatever argument is given for the city parameter when a new Store is instantiated; so when Seattle is instantiated, the value of the variable this.city will become "Seattle"
  this.city = city;
  // when Seattle is instantiated, the this.minHourlyCustomers variable will be assigned the value of the argument given for minHourlyCustomers which is 23
  this.minHourlyCustomers = minHourlyCustomers;
  this.maxHourlyCustomers = maxHourlyCustomers;
  this.avgCookiesPerCust = avgCookiesPerCust;
  this.hourlySales = hourlySales;
  this.dailySales = dailySales;
};

/*
So, essentially after Seattle is instantiated, the Seattle info is as follows (not correct syntax, just using for illustrative purposes)
  var city = 'Seattle'
  var minHourlyCustomers = 23
  var maxHourlyCusomters = 65
  var avgCookiesPerCustomer = 6.3
  var hourlySales = the array generated by the cookiesPerHour function -- e.g. [353, 265, 353, 239, 309, 372, 252, 164, 214, 183, 258, 176, 151, 328]
  var dailySales = the total calculated by cookiesPerDay function -- e.g. 4,500
*/

// adds a customerRandomizer function to the Store object; this function calculates a random number of customers within the min-max range
Store.prototype.customerRandomizer = function() {
  return Math.floor(Math.random() * (this.maxHourlyCustomers - this.minHourlyCustomers + 1) + this.minHourlyCustomers);
};

// adds a cookiesPerHour function to the Store object; this function takes the random customer number and multiplies it by average cookies per customer in order to get a cookies per hour amount
Store.prototype.cookiesPerHour = function() {
  // declares a variable named horlySales and sets its value to be an empty array
  // calculates a total for each hour open and pushes those hourly total values into the array declared immediately above
  for (var i = 0; i < storeHours.length; i++) {
    var cookieSales = Math.round(this.customerRandomizer() * this.avgCookiesPerCust);
    // for the Store object's variable named this.hourSales, the following sets that variable's value to an array of the values generated by this for loop
    this.hourlySales.push(cookieSales);
  }
  // pushes values (multple arrays) from the loop above into the globally-defined locationHourlySales array
  locationHourlySales.push(this.hourlySales);
};

// adds a cookiesPerDay function to the Store object; this function adds all the hourly sales for one store together
Store.prototype.cookiesPerDay = function() {
  this.dailySales = 0;
  for (var i = 0; i < storeHours.length; i++) {
    this.dailySales += this.hourlySales[i];
  }
};

function renderTableHeader() {
  var section = document.getElementById('cookiesales');
  var table = document.createElement('table');
  table.setAttribute ('id', 'table');
  section.appendChild(table);

  var thead = document.createElement('thead');
  table.appendChild(thead);

  var tr = document.createElement('tr');
  thead.appendChild(tr);

  var thStore = document.createElement('th');
  thStore.textContent = '';
  tr.appendChild(thStore);

  for(var i = 0; i < storeHours.length; i++){
    var thTime = document.createElement('th');
    thTime.textContent = `${storeHours[i]}`;
    tr.appendChild(thTime);
  }
  var thStoreTotal = document.createElement('th');
  thStoreTotal.textContent = 'Daily Total';
  tr.appendChild(thStoreTotal);
}

function renderTableFooter() {
  var table = document.getElementById('table');

  var tfoot = document.createElement('tfoot');
  table.appendChild(tfoot);

  var tr = document.createElement('tr');
  tr.setAttribute('id','totals');
  tfoot.appendChild(tr);

  var td = document.createElement('td');
  td.textContent = 'Hourly Total';
  tr.appendChild(td);

  var columnTotal = 0;
  for(var i = 0; i < storeHours.length; i++){
    // starting at zero--is this needed? maybe just so that you have the variable name
    var hourTotal = 0;
    for(var j = 0; j < locationHourlySales.length; j++){
      // is parseInt needed?
      hourTotal += parseInt(locationHourlySales[j][i]);
    }
    columnTotal += hourTotal;
    td = document.createElement('td');
    td.textContent = hourTotal;
    tr.appendChild(td);
  }
  td = document.createElement('td');
  td.textContent = columnTotal;
  tr.appendChild(td);
}

Store.prototype.renderSalesData = function(){
  var table = document.getElementById('table');
  var tr = document.createElement('tr');
  table.appendChild(tr);
  var th = document.createElement('th');
  th.textContent = `${this.city}`;
  tr.appendChild(th);
  // creates values for columns 2-15
  for(var i = 0; i < storeHours.length; i++){
    // haha on my last commit I didn't have an "i" below which is why it was rendering the whole array
    var sales = this.hourlySales[i];
    var td = document.createElement('td');
    td.textContent = sales;
    tr.appendChild(td);
  }
  // creates values for Daily Total Column
  td = document.createElement('td');
  td.setAttribute('class', 'total');
  td.textContent = `${this.dailySales}`;
  tr.appendChild(td);
};

// creates a listener for the submit event on the form in HTML
var storeForm = document.getElementById('addstore');
storeForm.addEventListener('submit', handleSubmit);

// creates a function that says what to do when event happens
function handleSubmit(e){
  e.preventDefault();
  var city = e.target.city.value;
  var mincustomers = e.target.mincustomers.value;
  var maxcustomers = e.target.maxcustomers.value;
  var avgcookies = e.target.avgcookies.value;
  var newStore = new Store(city, mincustomers, maxcustomers, avgcookies);
  newStore.renderSalesData();
}

(function renderAll(data){
  renderTableHeader();
  renderTableFooter();
  for(var i = 0; i < data.length; i++){
    data[i] = new Store(data[i][0], data[i][1], data[i][2], data[i][3], data[i][4], data[i][5]);
    data[i].cookiesPerHour();
    data[i].cookiesPerDay();
    data[i].renderSalesData();
  }
})(locationData);
